In [3]:
import numpy as np

In [23]:
a3 = np.random.randn(50, 10)

In [24]:
d3 =  np.random.randn(50, 10) < 0.8

In [25]:
a3

array([[ 2.75942910e+00, -1.70765902e+00, -1.63841810e+00,
         9.24703919e-01, -6.02348167e-01, -3.22218741e-01,
        -5.76141612e-01, -2.30138220e-01,  4.94462069e-01,
        -6.79993578e-01],
       [-2.26319043e-01, -4.44932082e-02, -4.62736735e-01,
        -2.43700786e-01,  8.15388040e-01, -9.24794428e-01,
         4.05448903e-01,  5.32373493e-01, -1.30798282e+00,
        -2.76975701e-01],
       [-2.26289886e+00, -7.43577274e-01,  2.97495914e-01,
         3.71527171e-01,  1.01348466e+00,  2.27606941e-01,
        -9.36164070e-01, -1.63233460e+00,  5.43620283e-02,
         1.20843246e+00],
       [-1.48766512e-01, -1.26889836e+00,  4.18596369e-01,
        -1.65820977e+00, -4.73229229e-01,  8.80007832e-01,
         4.22687770e-01, -3.84616275e-01, -8.57671425e-01,
         5.52893997e-01],
       [-4.03893663e-01,  6.50076150e-01, -4.61928638e-01,
        -6.76831230e-01, -9.06932499e-01, -7.96053031e-01,
         3.20678063e-01,  9.66886680e-01, -8.29968665e-01,
        -3.

In [26]:
d3

array([[ True,  True, False,  True,  True,  True,  True,  True,  True,
         True],
       [ True, False, False,  True,  True,  True, False, False,  True,
         True],
       [ True,  True,  True,  True,  True,  True, False,  True,  True,
         True],
       [ True,  True,  True,  True,  True, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True, False, False,  True,  True,
        False],
       [False,  True, False, False,  True,  True,  True, False,  True,
         True],
       [ True,  True,  True,  True,  True,  True, False,  True,  True,
         True],
       [False, False, False,  True,  True,  True,  True, False, False,
         True],
       [ True,  True,  True,  True, False,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True, False,  True,  True,  True,  True,
         True],
       [ True, False, False,  True,  True,  True,  True,  True, False,
         True],
       [False,  True, False,  True, False, 

In [27]:
a3 = np.multiply(a3, d3)

In [28]:
a3

array([[ 2.75942910e+00, -1.70765902e+00, -0.00000000e+00,
         9.24703919e-01, -6.02348167e-01, -3.22218741e-01,
        -5.76141612e-01, -2.30138220e-01,  4.94462069e-01,
        -6.79993578e-01],
       [-2.26319043e-01, -0.00000000e+00, -0.00000000e+00,
        -2.43700786e-01,  8.15388040e-01, -9.24794428e-01,
         0.00000000e+00,  0.00000000e+00, -1.30798282e+00,
        -2.76975701e-01],
       [-2.26289886e+00, -7.43577274e-01,  2.97495914e-01,
         3.71527171e-01,  1.01348466e+00,  2.27606941e-01,
        -0.00000000e+00, -1.63233460e+00,  5.43620283e-02,
         1.20843246e+00],
       [-1.48766512e-01, -1.26889836e+00,  4.18596369e-01,
        -1.65820977e+00, -4.73229229e-01,  0.00000000e+00,
         0.00000000e+00, -0.00000000e+00, -0.00000000e+00,
         0.00000000e+00],
       [-4.03893663e-01,  6.50076150e-01, -4.61928638e-01,
        -6.76831230e-01, -9.06932499e-01, -0.00000000e+00,
         0.00000000e+00,  9.66886680e-01, -8.29968665e-01,
        -0.

In [22]:
a3 / 0.8

array([[-0.        ],
       [ 0.        ],
       [-0.66193025],
       [ 1.39273684],
       [ 1.32923298]])